---
title: "Studier"
format: html
---

Sammenlikne studier: 

1: Block periodization of high-intensity aerobic intervals provides superior training effects in trained cyclists (2012). B.R. Rønnestad., J. Hansen & S. Ellefsen. DOI: 10.1111/j.1600-0838.2012.01485.x 

21 mannlige syklister (godt trente) deltok i studien. 19 fullførte. 10 stk i blokkperiodiseringsgruppa og 9 stk i tradisjonell gruppa. BP = én uke med 5 HIT økter + 3 uker med én HIT økt og resten rolig. TRAD = 2 x HIT økter pr uke, resten rolig. Samme volum av HIT og LIT i begge gruppene i løpet av de 4 ukene. 

HIT øktene ble gjennomført i sone 3 (88-100% av HR max). HIT øktene på sykkel 

Gjennomføring av Pre og Post test på sykkel i like omstendigheter. Siste HIT økt 2 dager før test. Måling av laktatprofil og VO2-maks: gjennomsnittet av de to høyeste VO2-målingene gjeldende som VO2maks. Hadde kriterier på om VO2maks var oppnådd ved bruk av HR, RER og LA. Noterte ned opplevd "anstrengelse" i beina i hver uke. HIT gruppa opplevde slitne bein under HIT-uka, men kom tilbake til utgangsnivået i løpet av de rolige ukene. TRAD-gruppa opplevde lik anstrengelse i beina under hele perioden. 

BP økte signifikant i VO2 maks, men det ikke var økning hos TRAD. 

Spesifikk spørsmål: Fører blokkperiodisering av HIT til økning i VO2maks kontra tradisjonell trening sett at den totale treningsmengden er lik, både når det gjelder HIT og LIT. 

Svakheter: Kun 4 uker -> én treningsintervensjon. 
Styrker: HIT og TRAD veldig lik treningsstatus før perioden, og treningsgrunnlag. De langvarige effektene forblir ukjente. Inneholder ingen prestasjonstest på sykkel.  

Hypotese: Antok at blokkperiodisering ville gi en overlegen effekt på VO2maks. 


2: Effects of 12 weeks of block periodization on performance and performance indices in well-trained cyclists

15 mannlige godt trente syklister deltok i studien. BP = 8 og TRAD = 7. BP = én uke med 5 HIT økter etterfulgt av 4 uker med én HIT økt. TRAD = 2 HIT økter hver uke. Gjennomførte dette i 12 uker. Det totale treningsvolumet og HIT økter var likt i begge gruppene. Likt utgangspunkt før treningsintervensjonen basert på treningserfaring og VO2maks. Likt LIT de siste 2 mnd før perioden. Gjennomført i forberedelsesperiode. 

Pre og post test. HIT øktene ble gjennomført i sone 3 (88-100% HR max), på sykkel. LIT øktene skulle ha en varighet på minimum 1 t i sone 1 (60-82% av HR max). De rapporterte opplevd anstrengelse i beina hver uke, i en skala fra 1-9. 

Testdag: En laktatprofil + VO2 maks test dag 1. Dag 2: 40 minutters all out. Siste HIT økt 3 dager før hver test. Ellers lik omstendigheter rundt hver test. Lik VO2maks test som studie 1. 

40 minutters all out test ble gjennomført etter 15 min oppvarming av eget ønske med innlagt 2-3 submaksimale drag. Mål om å sykle med så høy gjennomsnitts effekt som mulig. De styrte motstanden selv.

Statistikk: Presentert som gjennomsnitt +/- standardavvik. Uparret standard t-test brukt for å teste forskjellen mellom grupper ved baseline og treningsvolum. ANOVA test viste ingen forkskjeller mellom gruppene fra pre til post test. Grunn kan være lite utvalgstørrelse og godt trente personer. Derfor ble de brukt t-test og ES (kriterier for disse). Pre-intervensjonen til post-intervensjonen innenfor gruppeforskjeller ble sammenliknet ved bruk av parret student t-test av VO2maks. For å teste for relative forskjeller mellom gruppene ble uparret student t-test brukt. Større enn 0.05 i p-verdi ble ansett som signifikante. 

Like tester for å finne resultat i disse to studiene. 

Ingen signifikante forskjeller i gruppene før treningsintevensjonen. I ukene med HIT blokk opplevde HIT gruppe større opplevd anstrengelse i beina. Mens de resterende ukene var like mellom alle. 

Relativ endring i VO2 maks var større i BP enn hos TRAD. Gjennomsnitlig ES viste en moderat effekt av BP kontra TRAD. Større effekter i økning for VO2 maks hos BP enn hos TRAD. 

Hypotesen i denne studien antok at BP ville få store effekter på VO2 maks, laktatterskel, arbeidsøkonomi og 40 minutters prestasjonstest i forhold til TRAD. 

3: 5-week block periodization increases aerobic power in elite cross-country skiers

Sammenlikne effekten av organisering av utholdenhetstrening på elitelangrennsløpere som nærmer seg konkurranseperiode. 19 langrennsløpere deltok. 

BP (10) gjennomførte 5 uker, der uke 1 og 3 bestod av henholdsvis 5 og 3 HIT økter. En HIT økt i de resterende 3 ukene. TRAD (9) gjennomførte 2 x HIT økter hver uke, bortsett fra uke 3 der de gjennomførte 3 HIT økter. Det totale treningsvolumet og mengden HIT økter var likt mellom begge gruppene. Både kvinner og menn, skiskyttere og langrennsløpere. SKiskytterne var fordelt likt i begge gruppene. Tilfeldig inndelt på bakgrunn av VO2maks. De beste var blant topp 3 i nasjonale skirenn, mens de dårligste var topp 30. 

VO2 maks test ble kjørt på tredemølle skate før og etter intervensjonen. Trening i sone 3 ble gjennomført som HIT økter, 5x6 min eller 6x5 min. 50 % av HIT øktene skulle være skøyting på rulleski eller ski. BP og TRAD gjennomførte like mange HIT økter i skate. LIT øktene minimum 1 t i sone 1. 

Resultat: BP økte VO2maks signifikant, mens det ikke var noe økning hos TRAD. Effektstørrelsen av den relative forbedringene i disse målingene viste moderat effekt av BP kontra TRAD. Denne studien antyder at blokkperiodisering av utholdenhetstrening har overlegne effekter på flere utholdenhets- og prestasjonsindekser sammenlignet med tradisjonell organisering. 

Svakheter: ingen prestasjonstest. 
Styrker: også litt endring hos TRAD gruppa i form av én uke med 3 HIT økter. 

Samme volum av HIT og LIT på begge gruppene. 

Hypotese: Antar at BP vil gi en overlegen effekt på målinger på aerob kapasitet kontra TRAD. 

4: No Differences Between 12 Weeks of Block- vs. Traditional-Periodized Training in Performance Adaptations in Trained Cyclists

Formålet var å sammenliken effekten av 12 ukers blokkperiodisering ved bruk av konsentrerte HIT, MIT og LIT uker for BP, men blandingsuker av HIT, MIT og LIT for TRAD med en syklis progressiv økning i treningsbelastning over 4 og 12 uker hos trente syklister. 

Det var 30 deltakere med i studien. BP = 14 og TRAD = 16. Trente syklister. Det ble brukt en ukentlig syklus av progressiv belastning. Basert på gjennomsnittlige power output (PO) på en 40 mintters Time trial screening på sykkel ble deltakerne tifeldig fordelt i enten TRAD eller BP. TRAD: trente like uker med relativ lik fordeling av HIT, MIT og LIT. Mens BP: blokkerte periodiseringen i form av uker med kun HIT, MIT eller LIT trening. I den første meso-syklusen (4 uker) var uke 4 en restitusjonsuke for begge gruppene, og det totale timenatellet for HIT, MIT og LIT var likt i begge gruppene. MIT og HIT øktene var relativt like. Post test ble gjennomøført +/- 4-2 dager etter siste HIT/MIT økt. Den 4.uken i hver mesosyklus var en restitusjonsuke. Men denne ble brukt som en catch-up til de som ikke hadde gjennomført alle HIT/MIT øktene i de tidlgiere ukene. HIT øktene: 5x5 min og MIT = 4x12 min for BP. TRAD hadde eg progresjon med 4-5-6 x 5 min for de tre første HIT øktene og 3-4-5 for de MIT øktene (i hver mesosysklus).  Siste HIT og MIT økt var lik for begge gruppene for å sikre lik restitusjon foran test.  Brukte RPE som score på opplevd belastning. MIT: 14-18 og HIT: 16-19

De kunne gjennomføre alle HIT og MIT øktene under omsyn, men måtte gjennomføre 4 harde økter under tilsyn av testleder. Alle harde økter ble gjennomført på sykkel. 

Resultat: Gjennomførte én VO2maks test etter uke 4 (meso1) og etter uke 12. Ingen endring i VO2 maks i noen av gruppene mellom pre og post test. Studien viser altså ingen forskjell i treningseffekt (VO2maks) ved bruk av syklus med en progressiv økende treningsbelastnig hos trente syklister. Selv om HIT har vist seg å være overlegen MIT bare når det gjelder å forbedre VO2max og Wmax (Stoggl og Sperlich, 2014), kan det hevdes at MIT er en naturlig del av en godt utformet utholdenhetstreningsplan for utholdenhetstrene individer (Jones, 2006).

Ytelse og fysiologiske mål ble presentert som gjennomsnitt +/- SD. 

5: Block training periodization in alpine skiing: eVects of 11-day HIT on VO2max and performance

Hypotiserte at 11 dager mikrosyklus med 15 HIT økter vil føre til større økning i VO2 maks enn kontrollgruppa som trener konvensjonell mikset trening. 

21 trente alpintutøvere deltok i studien. Alle hadde trent regelmessig i over 3 år og deltatt i nasjonale FIS-renn. Gjennomført i forberedelsesperioden. Alle øktene ble gjennomført under kontrolerte omstendigheter på et treningssenter. HIT = 13 og TRAD = 8. Deltakerne ble gruppert randomisert på bakgrunn av lik VO2maks. Etter pre-test satte de i gang med 11 dagers treningsintervensjon. Post-test ble gjennomført 7 dager etter avsluttet intervensjon, og de fikk ikke trene hardt 24 t før test. BP gjennomførte blokker på tre dager med 1-2 HIT økter per dag, og hviledag på dag 4 og 8. HIT-øktene bestod av 4x4 med 90-95 % av HR max. Øktene ble enten gjennomført på sykkel-ergometersykkel eller i en ski-relatert hinderløypa. Deltakerne ble overvåket under HIT-intensiteten ble overvåket av HR og Borg, og øktene ble overvåket. BP gjennomførte beinstyrke på hviledagen og gjennomførte normal styrketrening på mage og overkropp. TRAD gruppa fortsatte sin normale trening. 

Totalt treningsvolum var signifikant lavere i BP gruppa kontra TRAD, men opplevd anstrengelse var større. Den totalt treningsbelastningen var dermed lik. VO2maks i forhold til kroppsmasse ble signifikant bedre hos BP, mens det ikke var endring hos TRAD. 

Like omstendigheter under pre og post-test. Alle testene ble utført på en ergometersykkel. 

Resultat: alle resultat presenteres som gjennomsnitt +/- SD. Forskjellen mellom gruppene ble testet ved (to-halet) students t-test for uparrede prøver. Mens endringer mellom deltakerne fra pre til post test ble testet for signifikant ved to-halet students t-test for parrede prøver. ANOVA ble brukt for å sammenlikne forskjeller mellom grupper og kjønn på to faktorer (intervensjon x tid). Resultatene ble signifikante ved en p-verdi på over 0.05. 




Total: 

Styrker: Alle HIT-økter ble gjennomført i bevegelsesformen som testingen ble gjennomført i. 
Siste HIT og MIT økt var lik for begge gruppene for å sikre lik restitusjon foran test.  

Svakheter: all trening gjennomført aleine på studie 1-4. 
