---
title: "Arbeidskrav 5 Studiedesign - rapport"
format: pdf
bibliography: referanser/referanser.bib
---

# Introduksjon

I denne rapporten er det valgt ut fem forskningsstudier som ser på effekten av blokkperiodisering sammenliknet med tradisjonell periodisering: @rønnestad2014a, @rønnestad2014b, @rønnestad2016, @almquist2022 og @breil2010. Studiene er analysert, og det er sett på studiedesign og statistiske analyser. I tillegg vil det bli presentert styrker og svakheter rundt studiene, og avslutningsvis gis det råd om hvordan fremtidige studier bør utformes i henhold til å besvare lignende spørsmål.

Felles for alle studiene er at de ser på blokklegging av utholdenhetstrening (BP = blokk-periodisering) sammenliknet med traidisjonell organisering av utholndehetstrening (TP = tradisjonall-periodisering). Studiene har sett på blant annet påvirkningen av det maksimale oksygenopptaket (VO$_{2maks}$), laktatterskel, submakismal og maksimal aerob effekt, prestasjonstester i ulike varianter og hemoglobinmasse (HB$_{mass}$). I studien til Almquist et al. (2022) er det også gjort muskulære analyser av deltakerne. Denne rapporten vil i hovedsak fokusere på hvilken effekten blokklegging har på VO$_{2maks}$. Rapporten tar dermed utgangspunkt i hovedproblemet til alle studiene: hvordan kan man best mulig optimalisere effekten på VO$_{2maks}$ ved å blokklegge utholdnehetstrening, framfor å trene tradisjonelt.  

Utformingen av studiene er naturligvis ikke helt like, og studiene er gjennomført på både syklister (@rønnestad2014a, @rønnestad2014b, @almquist2022), langrennsløpere og skiskyttere (@rønnestad2016) og alpinister (@breil2010). Alle studiene blokklegger høyintensiv trening (HIT), og sammenlikner dette opp mot tradisjonell strukturering av utholdenhetstrening. Tradisjonell utholdenhetstrening omhandler en kombinasjon av lavintensiv trening (LIT) og HIT. 


# Teori

Både LIT og HIT utholdenhetstrening har positive effekter på VO$_{2maks}$ (@helgerud2001; @helgerud2007; @ingham2008). Det ser også ut til at det er nødvendig med en kombinasjon av LIT og HIT for å oppnå optimal utvikling av utholdenhet (@seiler2010). For trente idrettsutøvere ser det likevel ut til at trening nær eller svært nær deres VO$_{2maks}$ er en effektiv stimuli for å ytterligere forbedre denne variabelen (@laursen2002). Hvordan man skal strukturere LIT og HIT for å omtimalisere utviklingen er fortsatt noe usikkert, og det er nettopp dette disse studiene i denne rapporter prøver å finne ut av.  

TP av utholdenhetstrening har gjennomgående handlet om to HIT-økter i uka, og ellers fylt opp med LIT (@seiler2004). Blokkperiodisering er kortere perioder (1-4 uker) der hovedfokuset er å forbedre spesifikke egenskaper, som VO$_{2maks}$, mens man skal vedlikeholde andre egenskaper. Tanken bak BP av utholdenhetstrening er å gi tilstrekkelig stimuli for å oppnå ytterligere tilpasninger hos godt trente idrettsutøvere, etterfulgt av restitusjon. Noen mener at dette ikke er mulig å oppnå ved et generelt fokus på mange egenskaper samtidig, slik som TP (@issurin2010). Det brede problemet som disse studiene prøver å finne løsningen på er hvordan man skal organisere utholdenhetstrening på for å oppnå en best mulig effekt på utholdenhetsvariabler ved BP, og sammenliknet dette opp med effekten som TP gir. 

Basert på denne teorien har studiene utformet sine egne hypoteser som i hovedsak går ut på at BP vil gi en betydelig større effekt på utholdenhetsvariabelen VO$_{2maks}$ sammenliknet med TP. Studien fra Almquist et al. (2022) skiller seg ut ved at den ikke har utviklet en hypotese eller et spørsmål, men formulerer likevel at målet med studien er å sammenlikne effekten av BP med TP. Det er logisk å tro at BP vil gi en positiv effekt på VO$_{2maks}$, men hvor stor effekten er i forhold til TP er vanskelig å si basert på teori. Utgangsnivået til deltakerne, og hvor mye de har trent tidligere, kan og tenkes å ha betydning for resultatet. Det kan være logisk å tro at deltakerne vil få en positiv effekt bare av det å endre treningssmønster. Har de trent mange år med TP, kan BP gi en positiv effekt fordi det gir et nytt stimuli.    

# Metode

## Studiedesign

Alle studiene er randomiserte kontrollerte studier (RCT) [@hulley2013]. I RCT blir deltakerne tilfeldig delt inn i grupper, og i disse studiene omhandler det to grupper, én intervensjonsgruppe (BP-gruppa) og én kontrollgruppe (TP-gruppa). Dette er et studiedesign som skal minimere skjevheter, og sikre at resultatene blir så pålitelige som mulig. På den måten ser man om resultatene som oppnås av studien har en virkelig effekt, og i hvilken grad. Risikoen for at andre faktorer påvirker resultatet minimeres ved en slik inndeling. I alle studiene ble det gjennomført en form for pre-test før gruppene ble randomisert. Utfallet av dette sørget for at det ikke var skjevheter i VO$_{2maks}$ hos gruppene før intervensjonen startet. Utgangspunktet og erfaringene til deltakerne skal dermed ikke ha noe påvirkning på resultatet av studien. To av studiene (@rønnestad2014a; @rønnestad2014b) er basert på samme forskningsprosjekt av samme deltakerutvalg og forskere, men studiene har sett på effekten av BP på henholdsvis fire og tolv uker.
 
Likevel er det litt ulik utforming av studiedesign i disse fem studiene. I studiene til @rønnestad2014a; @rønnestad2014b; @rønnestad2016; @almquist2022 er treninga til TP-gruppa nøye regulert og tatt kontroll over. På den måten sørger studiene for at de er helt sikre på at organiseringen av utholdenhetstreninga til gruppene er forskjellig. Det totale treningsvolumet av både HIT og LIT, og det totale antall HIT-økter var lik mellom begge gruppene i disse studiene. Treninga til BP-gruppa og TP-gruppa er dermed omtrent akkurat den samme, men organisert på forksjellige måter. Det gir stor pålitelighet for at resultatene av studien baserer seg på nettopp det de ønsker å finne ut av, effekten BP gir på VO$_{2maks}$ sammenliknet med TP.  

I studien til Breil et al. (2010) er det ikke formulert et opplegg til TP-gruppa. Studien har derfor ingen kontroll på hva denne gruppa har utført av trening under intervensjonsperioden. Det gir en større feilkilde når de sammenlikner effekten av BP sammenliknet med TP. 

## Deltakere og rekruttering

I studiene deltok det totalt 19, 15, 19, 30 og 21 [@rønnestad2014a; @rønnestad2014b; @rønnestad2016; @almquist2022; @breil2010] personer, og disse var fordelt tilnærmet likt mellom BP- og TP-gruppene. Deltakerne var ansett som godt trente i studiene til @rønnestad2014a; @rønnestad2014b; @almquist2022 (@pauw2013; @jeukendrup2000). I studiene til Rønnestad (2016) & Breil (2010) ble deltkaerne klassifisert som eliteutøvere basert på resultat i deres idrett. Deltakerne meldte seg enten på frivillig til å delta, (@rønnestad2014a; @rønnestad2014b; @rønnestad2016) eller ble rekruttert fra lokale sykkel- og alpintlag på og i nærheten av trenings- og testsenter (@almquist2022; @breil2010).  

Alle deltakerne ble informert om risikoer ved deltakelsen på forhånd, og måtte gi sitt skriftlige informerte samtykke før studiedeltakelsen. Disse studiene ble enten godkjent av den lokale etiske komite ved Høgskolen i Lillehammer eller den etiske komiteen i Bern, Sveits, og gjennomført i henhold til Helsinki-erklæringen. 

Ingen av studiene har begrunnet utvalgsstørrelsen, men flere opplyste om frafall av deltakere utover i intervensjonsperioden på bakgrunn av sykdom, medisinske årsaker eller for stor treningsbelastning. Det er dermed ikke gjort noen beregninger på hvor mange deltakere det hadde vært gunstig å hatt med i studiene. 

## Treningsintervensjon

Intervensjonsperioden på studiene varierte fra 11 dager til 12 uker.   BP-gruppene gjennoførte én uke med fem HIT-økter, og tre uker med én HIT-økt og resten LIT (@rønnestad2014a, @rønnestad2014b). I fem ukers studien til Rønnestad et al. (2016) ble det i tillegg lagt inn tre HIT-økter i uke tre. TP-gruppa fordelte ukene sine likt med to HIT-økter, og resten LIT-økter. Sett bort ifra TP-gruppa til Rønnestad et al. (2016) der det i uke tre ble gjennomført like mange HIT-økter som BP-gruppa.  

Studien til Almquist et al. (2022) skiller seg ut ved at de blokklagte både HIT, moderat intensivtrening (MIT) og LIT. Det vil si hver uke i én mesosyklus bestod av én HIT-uke, én MIT-uke og to LIT-uker for BP-gruppa. TP-gruppa kjørte blandingsuker av intensitet, men en syklis progressiv økning i treningsbelastning gjennom de fire ukene i hver mesosykus.

Studien til Breil et al. (2010) gjennomførte 15 HIT-økter på elleve dager. Hver fjerde dag var en restitusjonsdag, mens det ble gjennomført 1-2 hardøkter på de resterende i form av 4x4 min intervaller. 

Intensitetssonen som er brukt på HIT-øktene i studiene er sone 3, 88-100% av maksspuls (HR$_{maks}$). Dette tilsvarer intensitetssone 4/5 på olympiatoppens intensitetsskala for utholdenhet (@molmen2019). Alle HIT-øktene ble gjennomført i den spsifikke idretten de ble ansett som utøvere i. HIT-øktene bestod av enten 5x6 min, 6x5 min eller 5x5 min intervaller og MIT-øktene 4x12 min (@rønnestad2014a, @rønnestad2014b, @rønnestad2016, @almquist2022). Den progressive økningen i treningsbelastning ho TP-gruppa i Almquist et al. (2022) studien bestod av HIT-økter med en progresjon de første tre intervalløktene i hver syklus på 4-5-6 x 5 min intervaller og 3-4-5 x 12 min intervaller. I tillegg til puls ble det brukt opplevd anstrengelse i form av Borgs-skala som et mål på intensitet (@almquist2022, @breil2010).    


## Testing

Før intervensjonsperioden ble det gjennomført pre-tester av ulike varianter. rønnestad2014a; @rønnestad2014b; @rønnestad2016 og @breil2010 gjennomførte fysiske tester som bestemte VO$_{2maks}$, laktatprofil, maksimal aerob effekt (W$_{maks}$) og prestasjonstester over én eller to testdager. @almquist2022 gjennomførte fysiske tester over to testdager, og så på de samme variablene som de andre studiene. I likhet med Rønnestad et al. (2014b) ble det tatt hemoglobinmasse, i tillegg til muskelbiopsi i studien til Almquist et al. (2022). De fysiske testene ble gjennomført i samme aktivitetsform som HIT-øktene. 

I tillegg til å gjennomføre pre-test gjennomførte alle studiene en lik post-test, enten tre eller syv dager etter intervensjonen. Dette for å sikre at deltakerne var restituert etter treningsperioden. Studiene sørget for at forberedelsene til deltakerne, omstendighetene og testprosedyrene var så like som mulig på begge testene. I studien til Almquist et al. (2022) ble det gjennomført fysiske tester etter gjennomføring av én mesosyklus (4 uker) før de siste to mesosyklusene startet.   

## VO$_{2maks}$

Studiene tar utgangspunkt i variabelen VO$_{2maks}$ når de skal se på effekten av BP på deltakernes utvikling av aerob kapasitet. VO$_{2maks}$ er den høyeste hastigheten på den aerobe energiomsetningen (@åstrand2003), og er derfor regnet som en svært viktig bestemmende faktor for utholdenhetsprestasjon. For utholdenhetsprestasjon vil derfor faktorer som påvirker VO$_{2maks}$ være avgjørende å forbedre. Som skrevet tidligere har både HIT og LIT positiv effekt på aerob utholdenhet, målt som maksimalt oksygenopptak (@helgerud2001; @helgerud2007; @ingham2008). Forbedringer i denne variabelen avhenger av varighet, intensitet, hyppighet samt genetikk (@shephard1968; @wenger1986). Når utholdenhetsnivået til personer øker, ser det ut til at en økning i intensitet på den aerobe treningen er nødvendig for å oppnå en forbedring i VO$_{2maks}$ (@laursen2002). 

Dette er den utholdenhetsvariabelen som de fleste av disse studiene relaterer til i hypotesen, og ønsker å forbedre på bakgrunn av at dette øker utholdenhetsprestasjonen. 

## Statistiske analyser

RCT-studiedesignet til disse studiene gjenspeiler valget av de statistiske analysene. Ettersom studiene sammenlikner to grupper brukes et verktøy for å se korreleasjon mellom gruppene for å leite etter statistisk signifikans. Studiene til Rønnestad et al., 2014a, Rønnestad et al., 2014b og Rønnestad et al., 2016 regnet ut effektstørrelsen som Cohen's d for å finne statistisk signifikans. Kriteriene som var satt som grense for å tolke effektstørrelsen (ES) var følgende: 0.0--0.2 triviell, 0.2--0.6 liten, 0.6--1.2 moderat, 1.2--2.0 stor, og >2.0 veldig stor (@hopkins2009). 

Almquist et al. (2022) brukte heller en blandet lineær modell med grupper definert som «fixed effects» og korregert ved bruk av Pre-verdier som en kovarians med software SPSS v.25. 

Breil et al. (2010) regnet ut forskjellen mellom gruppene ved to-halet t-test for uparrede tester, mens for å se endringene mellom deltakerne fra pre- til post-test ble det brukt to-halet t-test for parrede tester. ANOVA ble brukt for å sammenlikne forskjeller mellom grupper og kjønn på to faktorer (intervensjon x tid). ANOVA ble også brukt i @rønnestad2014a, @rønnestad2014b, @rønnestad2016, men i noe ulik grad. I to av studiene ble en to-veis repeterende analyse av varians brukt for å evaluere differansen innad og mellom gruppene fra pre- til post-test. I @rønnestad2014a, @rønnestad2014b ble uparrede t-test brukt for å sammenligne gruppene ved baseline og gruppenes treningsvolum. Samtidig ble pre- til post-test sammenliknet ved bruk av parrede t-tester, og for å teste forskjellene mellom gruppene ble uparrede t-tester brukt.  


# Resultat

I fire av fem studier økte den relative VO$_{2maks}$ signifikant hos BP-gruppa, mens det ikke var økning hos TP-gruppa. ES av den relative forbedringen i VO$_{2maks}$ viser moderat til høy effket av BP sammenliknet med TP (@rønnestad2014a, @rønnestad2014b, @rønnestad2016, @breil2010).

I studien til Almquist et al. (2022), som gjennomførte VO$_{2maks}$-test etter både uke 4 og 12, var det ingen endring i VO$_{2maks}$ i noen av gruppene. Denne studien blokkperiodiserte både HIT, MIT og LIT, og TP-gruppa hadde en syklis progressiv økning i belastning utover i hver mesosyklus. 

Resultatene i fire av de fem analyserte studiene viser at blokkperiodisering av trening gir overlegne effekter på VO$_{2maks}$ sammenliknet med TP. Dette til tross for at treningsvolum og intensitet er lik mellom BP- og TP-gruppa.

Hypotesen i hver studiene ble besvart, og stemte overens med resultatet i fire av fem studier.


# Diskusjon




Studiene tar ikke for seg restitusjonstiltak. 

